export const TRAER_TODOS = 'clientes_traer_todos'
export const TRAER_UNO = 'clientes_traer_uno'
export const LOADING = 'clientes_cargando'
export const ERROR = 'clientes_error'
export const ERROR_FORM = 'clientes_error_form'
export const CAMBIO_ESTADO_FORM = 'clientes_cambio_estado_form'

export const CAMBIO_CLIENTE_ID = 'clientes_cambio_cliente_id'
export const CAMBIO_CLIENTE_RS = 'clientes_cambio_cliente_rs'
export const CAMBIO_CLIENTE_CUIL = 'clientes_cambio_cliente_cuil'
export const CAMBIO_CLIENTE_DOMICILIO = 'clientes_cambio_cliente_domicilio'
export const CAMBIO_CLIENTE_TELEFONO = 'clientes_cambio_cliente_telefono'
export const CAMBIO_CLIENTE_USER_ID = 'clientes_cambio_cliente_user_id'
export const CAMBIO_CLIENTE_EMPRESA_ID = 'clientes_cambio_cliente_empresa_id'

export const RECARGA = 'clientes_recarga_users'
export const CANCELAR = 'clientes_cancelar_users'
export const GUARDAR = 'clientes_guardar_user'