export const TRAER_TODOS = 'doctypes_traer_todos'
export const TRAER_UNO = 'doctypes_traer_uno'
export const LOADING = 'doctypes_cargando'
export const ERROR = 'doctypes_error'
export const ERROR_FORM = 'doctypes_error_form'
export const CAMBIO_ESTADO_FORM = 'doctypes_cambio_estado_form'

export const CAMBIO_DOCTYPE_ID = 'doctypes_cambio_doctype_id'
export const CAMBIO_DOCTYPE_NAME = 'doctypes_cambio_doctype_rs'
export const CAMBIO_DOCTYPE_TIPO = 'doctypes_cambio_doctype_cuil'
export const CAMBIO_DOCTYPE_OBLIGATORIO = 'doctypes_cambio_doctype_domicilio'
export const CAMBIO_DOCTYPE_ESTADO = 'doctypes_cambio_doctype_telefono'

export const RECARGA = 'doctypes_recarga_users'
export const CANCELAR = 'doctypes_cancelar_users'
export const GUARDAR = 'doctypes_guardar_user'