export const TRAER_TODOS = 'documentos_traer_todos'
export const TRAER_UNO = 'documentos_traer_uno'
export const LOADING = 'documentos_cargando'
export const ERROR = 'documentos_error'
export const ERROR_FORM = 'documentos_error_form'
export const CAMBIO_ESTADO_FORM = 'documentos_cambio_estado_form'

export const CAMBIO_DOCUMENTO_ID = 'documentos_cambio_documento_id'
export const CAMBIO_DOCUMENTO_RS = 'documentos_cambio_documento_rs'
export const CAMBIO_DOCUMENTO_CUIL = 'documentos_cambio_documento_cuil'
export const CAMBIO_DOCUMENTO_DOMICILIO = 'documentos_cambio_documento_domicilio'
export const CAMBIO_DOCUMENTO_TELEFONO = 'documentos_cambio_documento_telefono'

export const RECARGA = 'documentos_recarga_users'
export const CANCELAR = 'documentos_cancelar_users'
export const GUARDAR = 'documentos_guardar_user'