export const TRAER_TODOS = 'empresas_traer_todos'
export const TRAER_UNO = 'empresas_traer_uno'
export const LOADING = 'empresas_cargando'
export const ERROR = 'empresas_error'
export const ERROR_FORM = 'empresas_error_form'
export const CAMBIO_ESTADO_FORM = 'empresas_cambio_estado_form'

export const CAMBIO_EMPRESA_ID = 'empresas_cambio_empresa_id'
export const CAMBIO_EMPRESA_RS = 'empresas_cambio_empresa_rs'
export const CAMBIO_EMPRESA_CUIL = 'empresas_cambio_empresa_cuil'
export const CAMBIO_EMPRESA_DOMICILIO = 'empresas_cambio_empresa_domicilio'
export const CAMBIO_EMPRESA_TELEFONO = 'empresas_cambio_empresa_telefono'

export const RECARGA = 'empresas_recarga_users'
export const CANCELAR = 'empresas_cancelar_users'
export const GUARDAR = 'empresas_guardar_user'